language: python
env:
  global:
    - CC_TEST_REPORTER_ID: 4ec41efba1c82158ae6cb9981c186834c26d3e93ab69f396c284655235d8ca55
install: pip install tox coveralls flake8
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - flake8
  - tox
after_script:
   - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT --coverage-input-type coverage.py
after_success: coveralls

jobs:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8
      dist: xenial
    - python: pypy3
    - stage: deploy
      install: skip
      before_script: true
      script: true
      after_script: true
      after_success: true
      before_deploy: echo $TRAVIS_TAG > asciigraf/VERSION
      python: "3.6"
      deploy:
        provider: pypi
        skip_cleanup: true
        on:
          tags: true
        user: opusone
        password:
          secure: XTQJLPGnlkvJdGizMc8ZT9BldUghPw14BACJBr1Uzb1S2H9M+fzD12YwgWVZwHtYzPgAr/v6EaIM5ynDUteTyqCPSbZGvjaDcmjZfS/QFQ4iwMBSe9z4fk/GD5JQZ6pl0tvH/sb587STqhxN3MtCDfC9FCIM08wIkX7cLn//oalZRIqbtKTXPVqN6H0A1l0Tdlbk+TLEXxmbMIOdoFVhKEIYfkub7hVX4T+Jh1UI8+FUQUvUXp6EjUABvo85P9JfD1Xr2hJ9wK3sHCcNPzjvtRfqN6DkVPltoO0ZnqZMkFK78kW2m0zXEKQTUu2pyHaU+FzqIE7UKYD8uEECHl6ir1sRNKvRApE4vBl/UubHuKdEI0VvXy5a3019oocoiqMltaQjrU0Vk8vf6mEZeFRp/dbZD2DJbPQQ3mrGeFYYEAZ3zM3yWicPmPO4U6Kgy+tl+VCSdhv3HNiFLKC3nsRRKJD6LQTUTi49iIGRDpMZhvQSiO+q9/n1vtKFJr8v2yYPegVLtuipluNIhTz5mtjs++jYrRFnRPvXqzUVWIs7MihkG0mXlh1G1PF+cNuwGeR/Vk5eAxfD9OV+M9wOvVjy3qVEmk159v6QMPL6HyMu0ATHATUrOqFI2mbuiDJTXO38X2OlpigoS/MqeuaavBpdcGWHpfU0jsSijQG5LCUXUiQ=
