# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', 'pypy3.8', 'pypy3.9']
        networkx-version: ['2.4','2.5', '2.6', '2.7', '2.8', '3.0']
        include:
          - python-version: '3.7'
            networkx-version: '2.6'
          - python-version: '3.7'
            networkx-version: '1.11'
          - python-version: '3.8'
            networkx-version: '1.11'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[test]
        pip install networkx==${{ matrix.networkx-version }}
    - name: Lint with flake8
      run: |
        flake8
    - name: Test with Pytest
      run: |
        pytest --junitxml=junit/test-results.xml --cov-report term-missing  --cov-report=xml --cov-report=html --cov=asciigraf
